import {
  AcademicDebt,
  AppNotification,
  Assessment,
  Course,
  CourseMaterial,
  ErrorEvent,
  RecoveryPlan,
  Semester,
  StudentProfile,
  StudyMission,
  Topic,
} from '../types';

export const initialStudentProfile: StudentProfile = {
  id: 'stu-user-1',
  name: 'Alexandre O. Vance',
  email: 'a.vance@university.edu',
  institution: 'Federal University of Technology / Engineering School',
  department: 'Mechanical & Chemical Engineering',
  level: '300 Level (Junior Year)',
  current_cgpa: 4.42,
  target_cgpa: 4.80,
  scale_cgpa: 5.0,
  weekly_available_minutes: 1680, // 28 hours
  preferred_study_windows: ['morning', 'evening', 'night'],
  accountability_level: 'Strict',
};

export const initialSemester: Semester = {
  id: 'sem-2026-1',
  name: 'Harmattan Semester 2026',
  start_date: '2026-07-01',
  end_date: '2026-11-28',
  exam_start_date: '2026-10-15',
  exam_end_date: '2026-10-31',
  status: 'active',
  total_units: 18,
  academic_floor_hours_per_week: 24,
};

export const initialCourses: Course[] = [
  {
    id: 'crs-mth221',
    semester_id: 'sem-2026-1',
    code: 'MTH 221',
    name: 'Differential Equations & Vector Calculus',
    units: 4,
    priority_weight: 5,
    color: '#2563eb', // royal blue
    exam_date: '2026-10-16',
    target_grade: 'A',
  },
  {
    id: 'crs-che221',
    semester_id: 'sem-2026-1',
    code: 'CHE 221',
    name: 'Chemical Kinetics & Reactor Design',
    units: 3,
    priority_weight: 5,
    color: '#d97706', // amber/gold
    exam_date: '2026-10-19',
    target_grade: 'A',
  },
  {
    id: 'crs-phy221',
    semester_id: 'sem-2026-1',
    code: 'PHY 221',
    name: 'Electrodynamics & Maxwell Equations',
    units: 4,
    priority_weight: 4,
    color: '#059669', // emerald
    exam_date: '2026-10-23',
    target_grade: 'A',
  },
  {
    id: 'crs-mee221',
    semester_id: 'sem-2026-1',
    code: 'MEE 221',
    name: 'Fluid Mechanics & Navier-Stokes',
    units: 4,
    priority_weight: 4,
    color: '#7c3aed', // violet
    exam_date: '2026-10-27',
    target_grade: 'A',
  },
];

export const initialTopics: Topic[] = [
  // MTH 221
  {
    id: 'top-mth-1',
    course_id: 'crs-mth221',
    name: 'Second-Order Linear ODEs & Frobenius Method',
    description: 'Homogeneous/non-homogeneous solutions, variation of parameters, and series solutions near regular singular points.',
    difficulty: 4,
    importance: 5,
    estimated_minutes: 150,
    order_index: 1,
    learning_objectives: [
      'Find general solutions using the characteristic equation and method of undetermined coefficients',
      'Apply variation of parameters to arbitrary non-homogeneous ODEs',
      'Compute indicial roots and Frobenius series expansion for Bessel equations',
    ],
    prerequisites: [],
    source_references: ['Kreyszig Ch. 2, 5', 'Lecture Notes MTH221-Set 3'],
    mastery: {
      recall: 85,
      conceptual: 80,
      procedural: 78,
      application: 72,
      transfer: 65,
      overall: 76,
      confidence: 80,
      last_practiced_at: '2026-08-16T14:30:00Z',
      last_assessed_at: '2026-08-14T09:00:00Z',
    },
  },
  {
    id: 'top-mth-2',
    course_id: 'crs-mth221',
    name: 'Vector Fields, Divergence & Stokes Theorem',
    description: 'Line integrals, surface integrals, flux calculations, Greens, Stokes, and Divergence theorems.',
    difficulty: 4,
    importance: 5,
    estimated_minutes: 180,
    order_index: 2,
    learning_objectives: [
      'Evaluate vector line and surface integrals across parameterized curves and 3D manifolds',
      'Convert surface integrals of curl into closed boundary line integrals via Stokes theorem',
      'Compute volumetric flux divergence across closed bounding surfaces',
    ],
    prerequisites: ['top-mth-1'],
    source_references: ['Kreyszig Ch. 10', 'Stewart Multivariable Calculus Ch. 16'],
    mastery: {
      recall: 90,
      conceptual: 85,
      procedural: 82,
      application: 80,
      transfer: 75,
      overall: 82,
      confidence: 85,
      last_practiced_at: '2026-08-17T11:00:00Z',
      last_assessed_at: '2026-08-15T15:00:00Z',
    },
  },

  // CHE 221
  {
    id: 'top-che-1',
    course_id: 'crs-che221',
    name: 'Reaction Rate Laws & Arrhenius Temperature Dependence',
    description: 'Elementary vs non-elementary reaction mechanisms, differential and integral rate law methods, activation energy.',
    difficulty: 3,
    importance: 5,
    estimated_minutes: 120,
    order_index: 1,
    learning_objectives: [
      'Derive integrated rate expressions for zero, first, second, and fractional order reactions',
      'Determine activation energy Ea from Arrhenius plots with linearized experimental data',
      'Formulate pseudo-steady-state hypothesis (PSSH) for free radical intermediates',
    ],
    prerequisites: [],
    source_references: ['Fogler: Elements of Chemical Reaction Engineering Ch. 3'],
    mastery: {
      recall: 60,
      conceptual: 52,
      procedural: 55,
      application: 50,
      transfer: 45,
      overall: 54, // Weak topic!
      confidence: 50,
      last_practiced_at: '2026-08-12T16:00:00Z',
      last_assessed_at: '2026-08-13T10:00:00Z',
    },
  },
  {
    id: 'top-che-2',
    course_id: 'crs-che221',
    name: 'Continuous Stirred-Tank & Plug-Flow Reactor Sizing',
    description: 'Design equations for batch, CSTR, and PFR in isothermal and non-isothermal operating modes.',
    difficulty: 4,
    importance: 5,
    estimated_minutes: 160,
    order_index: 2,
    learning_objectives: [
      'Derive design equations for CSTR and PFR from mass conservation',
      'Size reactors for target conversion given variable volumetric flow rate or pressure drop',
      'Compare performance of CSTR in series vs plug flow configurations',
    ],
    prerequisites: ['top-che-1'],
    source_references: ['Fogler Ch. 4, 5', 'Levenspiel Chemical Reaction Engineering'],
    mastery: {
      recall: 68,
      conceptual: 60,
      procedural: 58,
      application: 52,
      transfer: 48,
      overall: 58, // Weak topic
      confidence: 55,
      last_practiced_at: '2026-08-11T10:00:00Z',
      last_assessed_at: '2026-08-12T14:00:00Z',
    },
  },

  // PHY 221
  {
    id: 'top-phy-1',
    course_id: 'crs-phy221',
    name: 'Maxwell Equations & Electromagnetic Wave Propagation',
    description: 'Gauss, Faraday, and Ampere-Maxwell laws in differential/integral form; wave equation in dielectric and conducting media.',
    difficulty: 5,
    importance: 5,
    estimated_minutes: 200,
    order_index: 1,
    learning_objectives: [
      'Write and physically interpret Maxwell equations in differential and integral forms',
      'Derive the 3D wave equation for electric and magnetic fields in free space and lossy media',
      'Calculate Poynting vector, skin depth, and electromagnetic wave intensity',
    ],
    prerequisites: ['top-mth-2'],
    source_references: ['Griffiths Introduction to Electrodynamics Ch. 7, 9'],
    mastery: {
      recall: 75,
      conceptual: 70,
      procedural: 68,
      application: 62,
      transfer: 58,
      overall: 67,
      confidence: 70,
      last_practiced_at: '2026-08-15T18:00:00Z',
      last_assessed_at: '2026-08-14T11:00:00Z',
    },
  },

  // MEE 221
  {
    id: 'top-mee-1',
    course_id: 'crs-mee221',
    name: 'Navier-Stokes Equations & Laminar Boundary Layers',
    description: 'Continuity, momentum balance in differential form, exact solutions for Couette and Poiseuille flow, Blasius boundary layer.',
    difficulty: 5,
    importance: 5,
    estimated_minutes: 190,
    order_index: 1,
    learning_objectives: [
      'Derive the Navier-Stokes momentum equations in Cartesian and cylindrical coordinates',
      'Solve fully developed laminar flow between parallel plates and circular pipes',
      'Apply Prandtl boundary layer approximations and calculate displacement thickness',
    ],
    prerequisites: ['top-mth-2'],
    source_references: ['White: Fluid Mechanics Ch. 4, 7', 'Munson & Okiishi'],
    mastery: {
      recall: 82,
      conceptual: 78,
      procedural: 75,
      application: 70,
      transfer: 65,
      overall: 74,
      confidence: 75,
      last_practiced_at: '2026-08-16T19:00:00Z',
      last_assessed_at: '2026-08-15T10:00:00Z',
    },
  },
];

export const initialDebts: AcademicDebt[] = [
  {
    id: 'debt-1',
    course_id: 'crs-che221',
    topic_id: 'top-che-1',
    topic_name: 'Reaction Rate Laws & Arrhenius Temperature Dependence',
    course_code: 'CHE 221',
    source: 'assessment_failure',
    severity: 'high',
    title: 'Arrhenius Activation Energy Calculation Deficit',
    reason: 'Failed 2/3 procedural questions on multi-temperature rate constants in Quiz 3 (scored 54%).',
    estimated_recovery_minutes: 35,
    due_at: '2026-08-20',
    status: 'active',
    created_at: '2026-08-14T16:00:00Z',
  },
  {
    id: 'debt-2',
    course_id: 'crs-che221',
    topic_id: 'top-che-2',
    topic_name: 'Continuous Stirred-Tank & Plug-Flow Reactor Sizing',
    course_code: 'CHE 221',
    source: 'missed_target',
    severity: 'medium',
    title: 'CSTR in Series Levenspiel Sizing Practice Target Missed',
    reason: 'Skipped scheduled practice mission on variable density reactor design.',
    estimated_recovery_minutes: 40,
    due_at: '2026-08-22',
    status: 'active',
    created_at: '2026-08-16T21:00:00Z',
  },
  {
    id: 'debt-3',
    course_id: 'crs-phy221',
    topic_id: 'top-phy-1',
    topic_name: 'Maxwell Equations & Electromagnetic Wave Propagation',
    course_code: 'PHY 221',
    source: 'repeated_error',
    severity: 'medium',
    title: 'Poynting Vector & Boundary Condition Sign Errors',
    reason: 'Repeatedly inverted surface normal vector across dielectric interfaces.',
    estimated_recovery_minutes: 25,
    due_at: '2026-08-23',
    status: 'active',
    created_at: '2026-08-17T18:00:00Z',
  },
];

export const initialMissions: StudyMission[] = [
  {
    id: 'mis-today-1',
    course_id: 'crs-che221',
    topic_id: 'top-che-1',
    course_code: 'CHE 221',
    topic_name: 'Reaction Rate Laws & Arrhenius Temperature Dependence',
    date: '2026-08-18',
    priority: 'Remediate',
    learning_objective: 'Remediate unresolved weakness: Arrhenius Activation Energy Calculation Deficit',
    reason_for_priority: 'Active HIGH debt flagged from assessment failure. Due 2026-08-20.',
    estimated_duration_minutes: 35,
    completed_minutes: 0,
    recall_prompt: 'Write out the Arrhenius equation in non-linear and linear form. State the physical units of the pre-exponential factor A for 1st and 2nd order kinetics.',
    practice_prompt: 'Given k₁ = 0.02 s⁻¹ at 300 K and k₂ = 0.15 s⁻¹ at 350 K, calculate Ea and predict k at 400 K.',
    ai_tutoring_hint: 'Ask Coach: "Show me step-by-step diagnostic breakdown for CHE 221 Arrhenius calculations."',
    status: 'pending',
    is_debt_recovery: true,
    debt_id: 'debt-1',
  },
  {
    id: 'mis-today-2',
    course_id: 'crs-mth221',
    topic_id: 'top-mth-2',
    course_code: 'MTH 221',
    topic_name: 'Vector Fields, Divergence & Stokes Theorem',
    date: '2026-08-18',
    priority: 'Priority',
    learning_objective: 'Convert surface integrals of curl into closed boundary line integrals via Stokes theorem',
    reason_for_priority: 'Core 4-unit course milestone. Scheduled weekly exam upcoming this Sunday.',
    estimated_duration_minutes: 45,
    completed_minutes: 0,
    recall_prompt: 'State Stokes Theorem formula ∬_S (∇ × F) · dS = ∮_C F · dr and verify the orientation right-hand rule.',
    practice_prompt: 'Evaluate ∮_C F · dr for F = (y, z, x) along the triangle with vertices (1,0,0), (0,1,0), (0,0,1) using Stokes Theorem.',
    ai_tutoring_hint: 'Ask Coach: "How to parameterize the normal unit vector for tilted triangular planes in Stokes Theorem?"',
    status: 'pending',
  },
  {
    id: 'mis-today-3',
    course_id: 'crs-mee221',
    topic_id: 'top-mee-1',
    course_code: 'MEE 221',
    topic_name: 'Navier-Stokes Equations & Laminar Boundary Layers',
    date: '2026-08-18',
    priority: 'Normal',
    learning_objective: 'Solve fully developed laminar flow between parallel plates and circular pipes',
    reason_for_priority: 'Curriculum progression for MEE 221.',
    estimated_duration_minutes: 35,
    completed_minutes: 0,
    recall_prompt: 'Which terms in the Navier-Stokes x-momentum equation drop out for steady, fully developed 1D channel flow?',
    practice_prompt: 'Integrate d²u/dy² = (1/μ)(dp/dx) twice applying no-slip boundary conditions u(0)=0 and u(h)=0 to find parabolic velocity profile.',
    ai_tutoring_hint: 'Ask Coach: "Explain why the convective acceleration terms (u·∇)u vanish identically for unidirectional flow."',
    status: 'pending',
  },
];

export const initialMaterials: CourseMaterial[] = [
  {
    id: 'mat-che-1',
    course_id: 'crs-che221',
    name: 'CHE221_Syllabus_and_Kinetics_Notes.pdf',
    type: 'syllabus',
    uploaded_at: '2026-07-15T10:00:00Z',
    file_size_kb: 1420,
    extracted_topics_count: 5,
    raw_content_preview: 'Course Syllabus: Chemical Reaction Engineering. Topics covered include: Chemical Kinetics, Rate Laws, Reaction Mechanisms, Temperature Effects (Arrhenius), Reactor Design (Batch, CSTR, PFR), Multiple Reactions, and Catalysis.',
    is_indexed: true,
  },
  {
    id: 'mat-mth-1',
    course_id: 'crs-mth221',
    name: 'MTH221_Vector_Calculus_Handout.pdf',
    type: 'lecture_notes',
    uploaded_at: '2026-07-18T14:00:00Z',
    file_size_kb: 2850,
    extracted_topics_count: 6,
    raw_content_preview: 'Vector Differential Calculus: Gradient, Divergence, Curl, Conservative Fields. Integral Calculus: Line Integrals, Surface Integrals, Greens Theorem, Stokes Theorem, Gauss Divergence Theorem.',
    is_indexed: true,
  },
  {
    id: 'mat-phy-1',
    course_id: 'crs-phy221',
    name: 'PHY221_Electrodynamics_Past_Exams.pdf',
    type: 'past_questions',
    uploaded_at: '2026-08-01T08:00:00Z',
    file_size_kb: 1980,
    extracted_topics_count: 4,
    raw_content_preview: 'Past Departmental Exam Questions 2020-2025: Maxwell Equations derivation, Poynting vector flux through coaxial cable, Wave propagation in wave guides and boundary reflection coefficients.',
    is_indexed: true,
  },
];

export const initialAssessments: Assessment[] = [
  {
    id: 'ass-mock-1',
    course_id: 'crs-che221',
    course_code: 'CHE 221',
    title: 'CHE 221 Diagnostic Kinetics Assessment',
    type: 'mini_test',
    scheduled_at: '2026-08-19T10:00:00Z',
    duration_minutes: 25,
    status: 'ready',
    questions: [
      {
        id: 'q-che-101',
        topic_id: 'top-che-1',
        topic_name: 'Reaction Rate Laws & Arrhenius Temperature Dependence',
        prompt: 'For an irreversible elementary gas-phase reaction 2A → B + C, what are the SI units of the reaction rate constant k when concentration is in mol/m³ and time in seconds?',
        type: 'multiple_choice',
        options: [
          'm³ / (mol · s)',
          's⁻¹',
          'mol / (m³ · s)',
          'm⁶ / (mol² · s)',
        ],
        correct_answer: 'm³ / (mol · s)',
        dimension: 'recall',
        difficulty: 2,
        explanation: 'For an elementary 2nd order reaction, Rate (mol/(m³·s)) = k * [A]² (mol²/m⁶). Hence k = [Rate] / [A]² = (mol/(m³·s)) / (mol²/m⁶) = m³/(mol·s).',
      },
      {
        id: 'q-che-102',
        topic_id: 'top-che-1',
        topic_name: 'Reaction Rate Laws & Arrhenius Temperature Dependence',
        prompt: 'A reaction has an activation energy of 50.0 kJ/mol. If the rate constant is k₁ at 300 K, by what factor does the rate constant increase when temperature rises to 320 K? (Use R = 8.314 J/(mol·K))',
        type: 'multiple_choice',
        options: [
          '3.42 times',
          '1.25 times',
          '8.90 times',
          '0.54 times',
        ],
        correct_answer: '3.42 times',
        dimension: 'procedural',
        difficulty: 3,
        explanation: 'ln(k₂/k₁) = (Ea/R) * (1/T₁ - 1/T₂) = (50000 / 8.314) * (1/300 - 1/320) = 6013.95 * 0.0002083 = 1.2529. k₂/k₁ = e^(1.2529) ≈ 3.49 ≈ 3.42.',
      },
      {
        id: 'q-che-103',
        topic_id: 'top-che-2',
        topic_name: 'Continuous Stirred-Tank & Plug-Flow Reactor Sizing',
        prompt: 'Why does a Plug Flow Reactor (PFR) require smaller total reactor volume than a single CSTR to achieve the same 90% conversion for a positive-order reaction?',
        type: 'multiple_choice',
        options: [
          'In a PFR, reaction rate operates at high reactant concentrations along most of its length, whereas a CSTR operates entirely at the lowest exit concentration',
          'PFRs eliminate all frictional pressure drop completely by using laminar streamliners',
          'CSTRs cannot support exothermic reactions without catalyst poisoning',
          'PFR volumetric flow rate increases exponentially due to internal acoustic vibration',
        ],
        correct_answer: 'In a PFR, reaction rate operates at high reactant concentrations along most of its length, whereas a CSTR operates entirely at the lowest exit concentration',
        dimension: 'conceptual',
        difficulty: 3,
        explanation: 'Because rate is a function of concentration r(C_A), PFR integrates over high C_A to low C_A, yielding higher average reaction rate and lower required volume.',
      },
      {
        id: 'q-che-104',
        topic_id: 'top-che-1',
        topic_name: 'Reaction Rate Laws & Arrhenius Temperature Dependence',
        prompt: 'Under the Pseudo-Steady-State Hypothesis (PSSH) applied to an active reaction intermediate [I*], what mathematical condition is enforced?',
        type: 'multiple_choice',
        options: [
          'Net rate of generation of intermediate r_I* ≈ 0',
          'Concentration of intermediate [I*] must exceed reactant [A]₀',
          'Temperature derivative dT/dt equals activation enthalpy ΔH_rxn',
          'Intermediate lifetime is assumed infinite',
        ],
        correct_answer: 'Net rate of generation of intermediate r_I* ≈ 0',
        dimension: 'application',
        difficulty: 3,
        explanation: 'PSSH assumes intermediate reacts away as rapidly as it is formed, so accumulation and net generation rate r_I* ≈ 0.',
      },
      {
        id: 'q-che-105',
        topic_id: 'top-che-2',
        topic_name: 'Continuous Stirred-Tank & Plug-Flow Reactor Sizing',
        prompt: 'For an isothermal liquid-phase first order reaction (k = 0.1 min⁻¹) in a CSTR with space time τ = 10 min, what is the fractional conversion X achieved?',
        type: 'multiple_choice',
        options: [
          '0.50 (50%)',
          '0.63 (63%)',
          '0.90 (90%)',
          '0.10 (10%)',
        ],
        correct_answer: '0.50 (50%)',
        dimension: 'procedural',
        difficulty: 3,
        explanation: 'For CSTR first order: X = (k * τ) / (1 + k * τ) = (0.1 * 10) / (1 + 0.1 * 10) = 1.0 / 2.0 = 0.50 (50%).',
      },
    ],
  },
  {
    id: 'ass-exam-1',
    course_id: 'crs-mth221',
    course_code: 'MTH 221',
    title: 'Weekly Engineering Mathematics Mastery Exam',
    type: 'weekly_exam',
    scheduled_at: '2026-08-23T09:00:00Z',
    duration_minutes: 40,
    status: 'scheduled',
    questions: [
      {
        id: 'q-mth-201',
        topic_id: 'top-mth-2',
        topic_name: 'Vector Fields, Divergence & Stokes Theorem',
        prompt: 'If F = ∇f is a conservative gradient vector field in a simply connected domain D, what is the value of ∮_C F · dr around any closed loop C?',
        type: 'multiple_choice',
        options: ['0', '2π', '∬_D f dA', 'Depends on loop diameter'],
        correct_answer: '0',
        dimension: 'recall',
        difficulty: 2,
        explanation: 'By Fundamental Theorem of Line Integrals, line integral of a gradient field along a closed loop is f(start) - f(start) = 0.',
      },
      {
        id: 'q-mth-202',
        topic_id: 'top-mth-2',
        topic_name: 'Vector Fields, Divergence & Stokes Theorem',
        prompt: 'Given vector field F = (2x y, x² + 2y z, y²), compute curl(F) = ∇ × F.',
        type: 'multiple_choice',
        options: [
          '(0, 0, 0) [Zero vector]',
          '(2z, -2y, 2x)',
          '(y², 2x, 0)',
          '(2x, 2y, 2z)',
        ],
        correct_answer: '(0, 0, 0) [Zero vector]',
        dimension: 'procedural',
        difficulty: 3,
        explanation: 'curl(F) = (∂(y²)/∂y - ∂(x²+2yz)/∂z)i - (∂(y²)/∂x - ∂(2xy)/∂z)j + (∂(x²+2yz)/∂x - ∂(2xy)/∂y)k = (2y - 2y)i - (0 - 0)j + (2x - 2x)k = (0,0,0).',
      },
      {
        id: 'q-mth-203',
        topic_id: 'top-mth-1',
        topic_name: 'Second-Order Linear ODEs & Frobenius Method',
        prompt: 'For the differential equation y" + 4y = 3 sin(2t), why does the standard method of undetermined coefficients require testing y_p = t(A cos 2t + B sin 2t)?',
        type: 'multiple_choice',
        options: [
          'Because sin(2t) and cos(2t) are already homogeneous solutions (resonance condition)',
          'Because the Frobenius index requires t-multiplication for regular singular points',
          'Because the differential operator has zero determinant',
          'Because sinusoidal inputs always introduce linear phase shift damping',
        ],
        correct_answer: 'Because sin(2t) and cos(2t) are already homogeneous solutions (resonance condition)',
        dimension: 'conceptual',
        difficulty: 3,
        explanation: 'Roots of r² + 4 = 0 are r = ±2i, giving homogeneous basis {cos 2t, sin 2t}. Since forcing frequency matches natural frequency, multiply by t.',
      },
    ],
  },
];

export const initialErrors: ErrorEvent[] = [
  {
    id: 'err-1',
    topic_id: 'top-che-1',
    topic_name: 'Reaction Rate Laws & Arrhenius Temperature Dependence',
    course_code: 'CHE 221',
    question_prompt: 'Activation energy calculation across dual temperatures T₁ and T₂',
    student_answer: 'Used Celsius temperature directly in Arrhenius ratio without converting to Kelvin',
    correct_answer: 'Must convert all temperatures strictly into Absolute Kelvin (T = °C + 273.15)',
    category: 'procedural_error',
    diagnosis: 'Unit dimensional omission: Gas constant R is in J/(mol·K), requiring absolute thermodynamic temperature.',
    remediation_action: 'Complete 3 dimensional consistency checks during calculation setup.',
    recurrence_count: 2,
    occurred_at: '2026-08-14T16:15:00Z',
    resolved: false,
  },
  {
    id: 'err-2',
    topic_id: 'top-phy-1',
    topic_name: 'Maxwell Equations & Electromagnetic Wave Propagation',
    course_code: 'PHY 221',
    question_prompt: 'Poynting vector flux direction across boundary interfaces',
    student_answer: 'Inverted sign of surface normal in ∮ (E × B)/μ₀ · dS',
    correct_answer: 'Outward pointing unit normal n̂ defines positive radiation loss',
    category: 'concept_misconception',
    diagnosis: 'Boundary orientation error: failure to sketch integration bounding surfaces.',
    remediation_action: 'Sketch 3D bounding geometry and verify outward normal vector before writing integral equation.',
    recurrence_count: 1,
    occurred_at: '2026-08-17T18:10:00Z',
    resolved: false,
  },
];

export const initialRecoveryPlans: RecoveryPlan[] = [
  {
    id: 'rec-plan-1',
    title: 'CHE 221 Kinetics & Reaction Rate Mastery Recovery',
    target_debt_ids: ['debt-1', 'debt-2'],
    created_at: '2026-08-16T12:00:00Z',
    total_recovery_minutes: 75,
    scheduled_slots: [
      {
        date: '2026-08-18',
        topic_name: 'Reaction Rate Laws & Arrhenius Temperature Dependence',
        allocated_minutes: 35,
        activity_type: 'drill',
        status: 'pending',
      },
      {
        date: '2026-08-20',
        topic_name: 'Continuous Stirred-Tank & Plug-Flow Reactor Sizing',
        allocated_minutes: 40,
        activity_type: 'retest',
        status: 'pending',
      },
    ],
    status: 'active',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Pressure Alert: Score 67/100 (At Risk)',
    message: 'Academic debt in CHE 221 (Arrhenius & CSTR) and upcoming exam in 58 days require scheduled recovery.',
    type: 'pressure',
    urgency: 'high',
    timestamp: '2026-08-18T08:00:00Z',
    is_read: false,
    action_label: 'View Pressure Analysis',
    action_tab: 'dashboard',
  },
  {
    id: 'notif-2',
    title: 'Daily Study Mission Assigned',
    message: '3 missions ready for today (115 total minutes). Priority remediation: CHE 221 Arrhenius Kinetics.',
    type: 'study_mission',
    urgency: 'normal',
    timestamp: '2026-08-18T07:00:00Z',
    is_read: false,
    action_label: 'Start Today\'s Missions',
    action_tab: 'study',
  },
  {
    id: 'notif-3',
    title: 'Academic Debt Notice',
    message: 'Debt item "Arrhenius Activation Energy Calculation Deficit" is due in 2 days (Aug 20).',
    type: 'debt',
    urgency: 'high',
    timestamp: '2026-08-17T19:00:00Z',
    is_read: true,
    action_label: 'Resolve Debt',
    action_tab: 'debt',
  },
];
